name: Build Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-firmware-t1616:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Image from GitHub Container Registry
        run: |
          docker pull ghcr.io/realdyllon/lightbrush/lightbrush-builder:latest

      - name: Build Firmware
        run: |
          docker run --rm -v .:/src ghcr.io/realdyllon/lightbrush/lightbrush-builder sp36-t1616

      - name: Upload Firmware
        uses: actions/upload-artifact@v2
        with:
          name: lightbrush.sofirn-sp36-t1616.hex
          path: ./firmware/spaghetti-monster/anduril/anduril.sofirn-sp36-t1616.hex

      - name: Set TAG_NAME environment variable
        run: |
          # Set TAG_NAME to the current date and time
          TAG_NAME=v$(date +'%Y%m%d_%H%M%S')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Create Tag For Release
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        env:
          # Create a tag based on the current date and time
          TAG_NAME: ${{ env.TAG_NAME }}
        with:
          tag: ${{ env.TAG_NAME }}
          tag_exists_error: false
          message: "Release ${{ env.TAG_NAME }}"

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          body: |
            This is an automatically generated release.
            It contains the latest version of Anduril for Sofirn SP36 with T1616 (and similar models, such as SP31 Pro).

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firmware/spaghetti-monster/anduril/anduril.sofirn-sp36-t1616.hex
          asset_name: lightbrush.sofirn-sp36-t1616.hex
          asset_content_type: application/octet-stream