name: Build Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-firmware-t1616:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Image from GitHub Container Registry
        run: |
          docker pull ghcr.io/RealDyllon/anduril-builder:latest

      - name: Build Firmware
        run: |
          docker run --rm -v .:/src anduril-builder sp36-t1616

      - name: Upload Firmware
        uses: actions/upload-artifact@v2
        with:
          name: anduril.sofirn-sp36-t1616.hex
          path: ./ToyKeeper/spaghetti-monster/anduril/anduril.sofirn-sp36-t1616.hex

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          draft: false
          prerelease: false
          body: |
            This is an automatically generated release.
            It contains the latest version of Anduril for Sofirn SP36 with T1616 (and similar models, such as SP31 Pro).
